In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.metrics import mean_squared_error

In [2]:
boston=load_boston()

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset 

In [3]:
df=pd.DataFrame(boston.data,columns=boston.feature_names)

In [4]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [5]:
y=pd.DataFrame(boston.target,columns=['price'])

In [6]:
y.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [7]:
df.shape

(506, 13)

In [8]:
y.shape

(506, 1)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB


In [10]:
X_train,X_test,y_train,y_test=train_test_split(df,y,test_size=0.3,random_state=1)

In [11]:
model=LinearRegression()

In [12]:
model.fit(X_train,y_train)

LinearRegression()

In [13]:
y_pred=model.predict(X_test)

In [14]:
mean_squared_error(y_test,y_pred)

19.831323672063235

## Lasso Regression

In [15]:
ls=Lasso()

In [16]:
ls.fit(X_train,y_train)

Lasso()

In [17]:
ls_pred=ls.predict(X_test)

In [18]:
mean_squared_error(y_test,ls_pred)

30.29379822196717

##  Ridge Regression

In [19]:
rg=Ridge()

In [20]:
rg.fit(X_train,y_train)

Ridge()

In [21]:
rg_pred=rg.predict(X_test)

In [22]:
mean_squared_error(y_test,rg_pred)

19.334416287843627

##  Running a FOR loop to get the best value of alpha(manual hyperparameter tuning) 

In [23]:
for i in range(1,11):
    rg=Ridge(alpha=i)
    rg.fit(X_train,y_train)
    rg_pred=rg.predict(X_test)
    print(f'the parameter {i} gives MSE as: {mean_squared_error(y_test,rg_pred)}')

the parameter 1 gives MSE as: 19.334416287843627
the parameter 2 gives MSE as: 19.34414257604263
the parameter 3 gives MSE as: 19.4087161997346
the parameter 4 gives MSE as: 19.481231131665123
the parameter 5 gives MSE as: 19.553270684503488
the parameter 6 gives MSE as: 19.623143690717452
the parameter 7 gives MSE as: 19.690667750560536
the parameter 8 gives MSE as: 19.75601602630487
the parameter 9 gives MSE as: 19.8194222582788
the parameter 10 gives MSE as: 19.881103543629216


In [24]:
for i in range(1,11):
    rg=Ridge(alpha=(i/1000))
    rg.fit(X_train,y_train)
    rg_pred=rg.predict(X_test)
    print(f'the parameter {i/1000} gives MSE as: {mean_squared_error(y_test,rg_pred)}')

the parameter 0.001 gives MSE as: 19.82974665728234
the parameter 0.002 gives MSE as: 19.828174783377907
the parameter 0.003 gives MSE as: 19.826608030581713
the parameter 0.004 gives MSE as: 19.825046379217767
the parameter 0.005 gives MSE as: 19.823489809701808
the parameter 0.006 gives MSE as: 19.82193830254079
the parameter 0.007 gives MSE as: 19.820391838332355
the parameter 0.008 gives MSE as: 19.818850397764333
the parameter 0.009 gives MSE as: 19.817313961614264
the parameter 0.01 gives MSE as: 19.8157825107489


In [25]:
param = [0.0001,0.001,0.01,0.1,0.5,0.7,0.9]
for i in param:
    rg=Ridge(alpha=i)
    rg.fit(X_train,y_train)
    rg_pred=rg.predict(X_test)
    print(f'the parameter {i} gives MSE as: {mean_squared_error(y_test,rg_pred)}')

the parameter 0.0001 gives MSE as: 19.8311657386803
the parameter 0.001 gives MSE as: 19.82974665728234
the parameter 0.01 gives MSE as: 19.8157825107489
the parameter 0.1 gives MSE as: 19.69619983181413
the parameter 0.5 gives MSE as: 19.427285232027753
the parameter 0.7 gives MSE as: 19.372925508852852
the parameter 0.9 gives MSE as: 19.343196176407435


In [26]:
param = [1e-15,1e-13,1e-11,1e-9,1e-7,1e-5,1e-3,1e-1,0.3,0.5,0.7,0.9,1,2,3,4,5,6,7,8,9,10,20,30,40,50,60,70,80,90,100,200,300,400,500]
for i in param:
    rg=Ridge(alpha=i)
    rg.fit(X_train,y_train)
    rg_pred=rg.predict(X_test)
    print(f'the parameter {i} gives MSE as: {mean_squared_error(y_test,rg_pred)}')

the parameter 1e-15 gives MSE as: 19.83132367206312
the parameter 1e-13 gives MSE as: 19.831323672062965
the parameter 1e-11 gives MSE as: 19.831323672047326
the parameter 1e-09 gives MSE as: 19.83132367048353
the parameter 1e-07 gives MSE as: 19.83132351410397
the parameter 1e-05 gives MSE as: 19.831307876402846
the parameter 0.001 gives MSE as: 19.82974665728234
the parameter 0.1 gives MSE as: 19.69619983181413
the parameter 0.3 gives MSE as: 19.523651928134928
the parameter 0.5 gives MSE as: 19.427285232027753
the parameter 0.7 gives MSE as: 19.372925508852852
the parameter 0.9 gives MSE as: 19.343196176407435
the parameter 1 gives MSE as: 19.334416287843627
the parameter 2 gives MSE as: 19.34414257604263
the parameter 3 gives MSE as: 19.4087161997346
the parameter 4 gives MSE as: 19.481231131665123
the parameter 5 gives MSE as: 19.553270684503488
the parameter 6 gives MSE as: 19.623143690717452
the parameter 7 gives MSE as: 19.690667750560536
the parameter 8 gives MSE as: 19.756016

In [27]:
rg=Ridge(alpha=1)
rg.fit(X_train,y_train)
rg_pred=rg.predict(X_test)
print(f'the parameter 1 gives MSE as: {mean_squared_error(y_test,rg_pred)}')

the parameter 1 gives MSE as: 19.334416287843627


In [28]:
param = [1e-15,1e-13,1e-11,1e-9,1e-7,1e-5,1e-3,1e-1,0.3,0.5,0.7,0.9,1,2,3,4,5,6,7,8,9,10,20,30,40,50,60,70,80,90,100,200,300,400,500]
for i in param:
    ls=Lasso(alpha=i)
    ls.fit(X_train,y_train)
    ls_pred=ls.predict(X_test)
    print(f'the parameter {i} gives MSE as: {mean_squared_error(y_test,ls_pred)}')

the parameter 1e-15 gives MSE as: 19.831323672063103
the parameter 1e-13 gives MSE as: 19.831323672061078
the parameter 1e-11 gives MSE as: 19.831323671856893
the parameter 1e-09 gives MSE as: 19.831323651438982
the parameter 1e-07 gives MSE as: 19.831321609667693
the parameter 1e-05 gives MSE as: 19.831117462584942
the parameter 0.001 gives MSE as: 19.81103120725189
the parameter 0.1 gives MSE as: 20.22471700674124
the parameter 0.3 gives MSE as: 21.987596152983613
the parameter 0.5 gives MSE as: 23.91888317593273
the parameter 0.7 gives MSE as: 26.208685323837656
the parameter 0.9 gives MSE as: 28.86342585454826
the parameter 1 gives MSE as: 30.29379822196717
the parameter 2 gives MSE as: 35.408678173317455
the parameter 3 gives MSE as: 38.89068851985193
the parameter 4 gives MSE as: 40.98078900621156
the parameter 5 gives MSE as: 41.78563872008822
the parameter 6 gives MSE as: 42.70060909352538
the parameter 7 gives MSE as: 43.658204119875215


C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.152e+03, tolerance: 2.874e+00
  model = cd_fast.enet_coordinate_descent(


the parameter 8 gives MSE as: 44.04998191825928
the parameter 9 gives MSE as: 44.4826470264785
the parameter 10 gives MSE as: 44.956169817731784
the parameter 20 gives MSE as: 51.93799937435368
the parameter 30 gives MSE as: 65.21056747930224
the parameter 40 gives MSE as: 65.56771206363891
the parameter 50 gives MSE as: 66.2719587479431
the parameter 60 gives MSE as: 66.83865058669218
the parameter 70 gives MSE as: 67.13122629210736
the parameter 80 gives MSE as: 67.45022936233622
the parameter 90 gives MSE as: 67.79567582171714
the parameter 100 gives MSE as: 68.16745703715412
the parameter 200 gives MSE as: 71.51859818639382
the parameter 300 gives MSE as: 74.68039405217618
the parameter 400 gives MSE as: 78.49124889573748
the parameter 500 gives MSE as: 82.95116271707771


In [29]:
ls=Lasso(alpha=0.001)
ls.fit(X_train,y_train)
ls_pred=ls.predict(X_test)
print(f'the parameter 0.001 gives MSE as: {mean_squared_error(y_test,ls_pred)}')

the parameter 0.001 gives MSE as: 19.81103120725189


## Hyperparameter Tuning using GridSearchCV 

In [30]:
param={'alpha':[1e-15,1e-13,1e-11,1e-9,1e-7,1e-5,1e-3,1e-1,0.3,0.5,0.7,0.9,1,2,3,4,5,6,7,8,9,10,20,30,40,50,60,70,80,90,100,200,300,400,500]}

In [31]:
model_ls = GridSearchCV(Lasso(),param)

In [32]:
model_ls.fit(df,y)  #donot fit it on X_train & y_train bcz we can set CV(cross validation) over here

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.431e+03, tolerance: 3.919e+00
  model = cd_fast.enet_coordinate_descent(
C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.397e+03, tolerance: 3.307e+00
  model = cd_fast.enet_coordinate_descent(
C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.797e+03, toler

GridSearchCV(estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-13, 1e-11, 1e-09, 1e-07, 1e-05,
                                   0.001, 0.1, 0.3, 0.5, 0.7, 0.9, 1, 2, 3, 4,
                                   5, 6, 7, 8, 9, 10, 20, 30, 40, 50, 60, 70,
                                   80, 90, ...]})

In [33]:
model_ls.best_params_

{'alpha': 0.9}

In [34]:
model_rg = GridSearchCV(Ridge(),param)

In [35]:
model_rg.fit(df,y)

GridSearchCV(estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-13, 1e-11, 1e-09, 1e-07, 1e-05,
                                   0.001, 0.1, 0.3, 0.5, 0.7, 0.9, 1, 2, 3, 4,
                                   5, 6, 7, 8, 9, 10, 20, 30, 40, 50, 60, 70,
                                   80, 90, ...]})

In [36]:
model_rg.best_params_

{'alpha': 200}

In [37]:
ls=Lasso(alpha=0.9)
ls.fit(X_train,y_train)
ls_pred=ls.predict(X_test)
print(f'the parameter 0.9 gives MSE as: {mean_squared_error(y_test,ls_pred)}')

the parameter 0.9 gives MSE as: 28.86342585454826


In [38]:
rg=Ridge(alpha=200)
rg.fit(X_train,y_train)
rg_pred=rg.predict(X_test)
print(f'the parameter 200 gives MSE as: {mean_squared_error(y_test,rg_pred)}')

the parameter 200 gives MSE as: 24.866262116872758


##  CrossValidation

In [49]:
CV=cross_val_score(estimator=LinearRegression(),X=df,y=y,cv=10)
CV

array([ 0.73376082,  0.4730725 , -1.00631454,  0.64113984,  0.54766046,
        0.73640292,  0.37828386, -0.12922703, -0.76843243,  0.4189435 ])

In [50]:
CV.mean()

0.2025289900605657

In [39]:
CV=cross_val_score(estimator=LinearRegression(),X=df,y=y,cv=10,scoring='neg_mean_squared_error')

In [40]:
CV

array([  -9.28694671,  -14.15128316,  -14.07360615,  -35.20692433,
        -31.88511666,  -19.83587796,   -9.94726918, -168.37537954,
        -33.32974507,  -10.96041068])

In [41]:
CV.mean()

-34.705255944524815

In [42]:
np.mean(CV)

-34.705255944524815

In [43]:
CV_ls=cross_val_score(estimator=Lasso(),X=df,y=y,cv=10,scoring='neg_mean_squared_error')

In [44]:
CV_ls

array([ -11.75904887,  -17.87218543,  -10.52504673,  -60.79224355,
        -46.77806854,  -40.75196077,  -17.30562005, -102.67754279,
        -22.8731834 ,  -13.30594575])

In [45]:
CV_ls.mean()

-34.46408458830233

In [46]:
CV_rg=cross_val_score(estimator=Ridge(),X=df,y=y,cv=10,scoring='neg_mean_squared_error')

In [47]:
CV_rg

array([  -9.31766315,  -12.60806897,  -10.79859434,  -36.6093648 ,
        -29.62109212,  -18.62598134,   -9.46641896, -168.49831117,
        -33.79749469,  -11.43947255])

In [48]:
CV_rg.mean()

-34.07824620925929