In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
df=pd.read_excel('MYNTRA Data..xlsx')

In [3]:
df

Time (Mins)  Recall Rate
0             1         0.84
1             5         0.71
2            15         0.61
3            30         0.56
4            60         0.54
5           120         0.47
6           240         0.45
7           480         0.38
8           720         0.36
9          1440         0.26
10         2880         0.20
11         5760         0.16
12        10080         0.08

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Time (Mins)  13 non-null     int64  
 1   Recall Rate  13 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 336.0 bytes


In [5]:
df.describe()

Time (Mins)  Recall Rate
count     13.000000    13.000000
mean    1679.307692     0.432308
std     3018.230508     0.222567
min        1.000000     0.080000
25%       30.000000     0.260000
50%      240.000000     0.450000
75%     1440.000000     0.560000
max    10080.000000     0.840000

In [6]:
df1=df.copy()

In [58]:
#df1['Log(Time)']=np.log(df['Time (Mins)'])
#df1.drop(['Time (Mins)'],axis=1)
#y=df1['Recall Rate']
#x=df1[['Log(Time)']]

In [59]:
df1['sqrt(Time)']=np.sqrt(df['Time (Mins)'])
df1.drop(['Time (Mins)'],axis=1)
y=df1['Recall Rate']
x=df1[['sqrt(Time)']]

In [61]:
#df1['exp(Time)']=np.exp(df['Time (Mins)'])
#df1.drop(['Time (Mins)'],axis=1)
#y=df1['Recall Rate']
#x=df1[['exp(Time)']]

In [62]:
#df1['1/Time']=np.reciprocal(df['Time (Mins)'])
#df1.drop(['Time (Mins)'],axis=1)
#y=df1['Recall Rate']
#x=df1[['1/Time']]

In [63]:
x

sqrt(Time)
0     1.000000
1     2.236068
2     3.872983
3     5.477226
4     7.745967
5    10.954451
6    15.491933
7    21.908902
8    26.832816
9    37.947332
10   53.665631
11   75.894664
12  100.399203

In [64]:
y

0     0.84
1     0.71
2     0.61
3     0.56
4     0.54
5     0.47
6     0.45
7     0.38
8     0.36
9     0.26
10    0.20
11    0.16
12    0.08
Name: Recall Rate, dtype: float64

In [65]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [66]:
x_train

sqrt(Time)
1     2.236068
6    15.491933
0     1.000000
7    21.908902
12  100.399203
9    37.947332
8    26.832816
11   75.894664
5    10.954451

In [67]:
model=LinearRegression()

In [68]:
model.fit(x_train,y_train)

LinearRegression()

In [69]:
y_pred=model.predict(x_test)

In [70]:
r2_score(y_test,y_pred)

0.9240670955724543

In [71]:
c=model.intercept_
c

0.614635163845186

In [72]:
m=model.coef_
m

array([-0.00622457])

In [74]:
y_in=0.5
x_out=(y_in-c)/m
x_out

array([18.41655551])

In [75]:
#time=np.exp(x_out)
time=x_out*x_out
#time=np.log(x_out)
#time=1/x_out

In [76]:
time

array([339.16951696])

In [77]:
new_record=[[5000]]

In [78]:
transform_record=np.sqrt(new_record)

In [79]:
model.predict(transform_record)

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.1744915])